# Generated by Django 3.2.9 on 2021-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicEntry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=20)),
                ('DoctorGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('DoctorContact', models.CharField(max_length=20)),
                ('DoctorEmail', models.EmailField(max_length=20, unique=True)),
                ('HospitalAddress', models.TextField()),
                ('QualCertificate', models.FileField(upload_to='Uploads/DoctorCertificate/')),
                ('DoctorPhoto', models.FileField(upload_to='Uploads/DoctorImage/')),
                ('DoctorUsername', models.CharField(max_length=20)),
                ('DoctorPassword', models.CharField(max_length=20)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicEntry.district')),
            ],
        ),
        migrations.CreateModel(
            name='DrQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.doctor')),
                ('Qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicEntry.qualification')),
            ],
        ),
    ]
