# Generated by Django 3.2.9 on 2021-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopOwner', '0001_initial'),
        ('Admin', '0001_initial'),
        ('BasicEntry', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.TextField()),
                ('PetCertificate', models.FileField(upload_to='Uploads/PetCertftoDoctor/')),
                ('Date', models.DateField(auto_now=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.doctor')),
                ('PetCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.petcategory')),
                ('PetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Petcolor', models.CharField(max_length=20)),
                ('PetGender', models.CharField(max_length=20)),
                ('PetBreed', models.CharField(max_length=20)),
                ('PetBreedCombination1', models.CharField(max_length=20, null=True)),
                ('PetBreedCombination2', models.CharField(max_length=20, null=True)),
                ('PetImage', models.FileField(upload_to='Uploads/PetImage/')),
                ('PetCertificate', models.FileField(upload_to='Uploads/PetCertificate/')),
                ('PetCertificateId', models.CharField(max_length=20)),
                ('PetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
                ('PetSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GallaryImage', models.FileField(upload_to='Uploads/GallaryImage/')),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetOwner.pet')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintData', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('Reply', models.CharField(max_length=1000, null=True)),
                ('Status', models.IntegerField(default=0)),
                ('ComplaintType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicEntry.complainttype')),
                ('PetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('TotalPrice', models.FloatField()),
                ('Date', models.DateField(auto_now=True)),
                ('Status', models.IntegerField(default=0)),
                ('PetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopOwner.product')),
            ],
        ),
        migrations.CreateModel(
            name='BuyPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_ofPets', models.IntegerField()),
                ('TotalPrice', models.FloatField()),
                ('Date', models.DateField(auto_now=True)),
                ('Status', models.IntegerField(default=0)),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopOwner.petsale')),
                ('PetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
            ],
        ),
    ]
