# Generated by Django 3.2.9 on 2021-12-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petdisease',
            name='PetCategory',
        ),
        migrations.AddField(
            model_name='petdisease',
            name='Pet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PetOwner.pet'),
            preserve_default=False,
        ),
    ]
