# Generated by Django 3.2.9 on 2021-12-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0002_auto_20211208_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petdisease',
            name='PetCertificate',
        ),
    ]
