# Generated by Django 3.2.9 on 2021-12-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0003_remove_petdisease_petcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdisease',
            name='Reply',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='petdisease',
            name='Status',
            field=models.BooleanField(default=0),
        ),
    ]
