# Generated by Django 3.2.9 on 2021-12-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0007_auto_20211221_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petdisease',
            old_name='DrMeetingLink',
            new_name='DrMeetingCode',
        ),
    ]
