# Generated by Django 3.2.9 on 2021-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0008_rename_drmeetinglink_petdisease_drmeetingcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdisease',
            name='FeesStatus',
            field=models.BooleanField(default=0),
        ),
    ]
