# Generated by Django 3.2.10 on 2021-12-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetOwner', '0009_petdisease_feesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buypet',
            name='TotalPrice',
            field=models.CharField(max_length=10),
        ),
    ]
