# Generated by Django 3.2.9 on 2021-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintType', models.CharField(max_length=20, unique=True, verbose_name='ComplaintType')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=20, unique=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PetCategory', models.CharField(max_length=20, unique=True, verbose_name='PetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCategory', models.CharField(max_length=20, unique=True, verbose_name='ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=20, unique=True, verbose_name='Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory', models.CharField(max_length=20, unique=True, verbose_name='SubCategory')),
                ('PetCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.petcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductsubCategory', models.CharField(max_length=20, unique=True, verbose_name='ProductsubCategory')),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=20, unique=True, verbose_name='Place')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.district')),
            ],
        ),
    ]
