# Generated by Django 3.2.9 on 2021-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicEntry', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComplaintData', models.TextField()),
                ('Date', models.DateField(auto_now=True)),
                ('Reply', models.CharField(max_length=1000, null=True)),
                ('Status', models.IntegerField(default=0)),
                ('ComplaintType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicEntry.complainttype')),
                ('ShopOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductRate', models.FloatField()),
                ('ProductDiscription', models.CharField(max_length=20)),
                ('ProductImage', models.FileField(upload_to='Uploads/ProductImage/')),
                ('ProductStock', models.IntegerField(default=0)),
                ('ProductPetCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicEntry.petcategory')),
                ('ProductProductsubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.productsubcategory')),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PetSaleColor', models.CharField(max_length=20)),
                ('PetSaleGender', models.CharField(max_length=20)),
                ('PetSaleBreed', models.CharField(max_length=20)),
                ('PetSaleBreedCombination1', models.CharField(max_length=20, null=True)),
                ('PetSaleBreedCombination2', models.CharField(max_length=20, null=True)),
                ('PetSaleImage', models.FileField(upload_to='Uploads/PetSaleImages/')),
                ('PetSaleCertificate', models.FileField(upload_to='Uploads/PetSaleCertificates/')),
                ('PetSaleCertificateId', models.CharField(max_length=20)),
                ('PetSaleStock', models.IntegerField(default=0)),
                ('PetSaleRate', models.FloatField()),
                ('PetSaleSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicEntry.subcategory')),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.shop')),
            ],
        ),
    ]
