# Generated by Django 3.2.10 on 2021-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopOwner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsale',
            name='PetSaleRate',
            field=models.CharField(max_length=10),
        ),
    ]
