# Generated by Django 3.2.9 on 2021-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideosCaption', models.CharField(max_length=20)),
                ('VideosDescription', models.TextField(max_length=20)),
                ('VideosVideo', models.FileField(upload_to='Uploads/MedicalVideos/')),
                ('VideoDate', models.DateField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.doctor')),
            ],
        ),
    ]
